### ISSUE TITLE
Testing Database ORM

### ISSUE THREAD

**Issue by francescobianco** [adawolfa/anemic#1]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by adawolfa** [comment]
Hello there, this project is in very early stage of development with a lot of work ahead. There's no roadmap yet and the one in my head is keep changing every day. Once I've got an initial release with all the features I want, I will reconsider this, but for now - I'm not going to integrate this.

I like your project as it seems to be way simpler to use than the Doctrine - which is, of course, handy, when writing smaller or less complex applications.

However, I'm not going to integrate any new features (excluding those mentioned in readme) for now, as I personally don't need them.

Please note, that this framework by default uses Nette DI container, which supports container compiler extensions. With an extension, you can easily integrate Moldable into any Anemic or Nette Framework application. See list of already implemented ORM integrations [here](https://componette.com/search/orm).

This is the best suggestion I can give - with Nette DI extension, much more applications will get covered!

Thank you and keep up a good work.

**Comment by francescobianco** [comment]
@adawolfa Please, could you install the library and give me a feedback if there is something wrong?
